version: '3'

services:
  app:
    build: .
    tty: true
    volumes:
      - ./src:/src
    working_dir: "/src"
    environment:
        LOCAL_USER: ${LOCAL_USER:-}
        LOCAL_UID: ${LOCAL_UID:-}
        LOCAL_GID: ${LOCAL_GID:-}