version: '3'

services:
  app:
    build: .
    image: node-dev-env
    #image: node:lts
    container_name: node-dev2
    tty: true
    volumes:
      - ./src:/src
    working_dir: "/src"
    environment:
        LOCAL_USER: ${LOCAL_USER:-}
        LOCAL_UID: ${LOCAL_UID:-}
        LOCAL_GID: ${LOCAL_GID:-}