version: '3'

services:
  app:
    build: .
    #image: node-dev-env
    tty: true
    volumes:
      - ./src:/src
    working_dir: "/src"
    ports: 
      - "3000:3000"
    environment:
        LOCAL_USER: ${LOCAL_USER:-}
        LOCAL_UID: ${LOCAL_UID:-}
        LOCAL_GID: ${LOCAL_GID:-}